blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Q&A Forum
    url: https://github.com/web3phl/matuto/discussions/new?category=q-a
    about: Have a question? Let us know!
  - name: ğŸ§  Suggestions
    url: https://github.com/web3phl/matuto/discussions/new?category=brainstorming
    about: Have an idea, suggestions or feedback? Let us know!